object_ids:
  '22': Pringles Rice Fusion
  '23': Pringles Pringoooals
  '24': Pringles Original
#  '11': Turing picture
#  '12': Peacock picture
#  '13': Fruit picture
#  '14': Landscape picture
#  '15': Robot picture
#  '16': Lumberjack picture
